# Site settings
title: This is me
header-img: img/home-bg.jpg
email: howardpanton@gmail.com
copyright_name: Howard Panton
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "https://howardpanton.github.io"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  StartBootstrap
email_username:  your-email@yourdomain.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
